subtitle = "It's not too late to turn back!"
keywords = ""

[author]
    name = "Sloth"
    email = "sloth@sloth.direct"

[header]
    logo = "logo.svg"

[footer]
    since = 2025
    poweredby = true

[social_media]
    [[social_media.items]]
    enabled = true
    title = 'Bluesky'
    icon = 'brand-bluesky'
    link = 'https://bsky.app/profile/sloth.direct'

    [[social_media.items]]
    enabled = true
    title = 'Mastodon'
    icon = 'user'
    link = 'https://guild.pmdcollab.org/@sloth'

[manifest]
    description = "It's not too late to turn back!"

